"""drop_tags_column

Revision ID: 08154c1e22f4
Revises: 11bfda37d908
Create Date: 2026-04-10 10:36:17.806289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08154c1e22f4'
down_revision: Union[str, Sequence[str], None] = '11bfda37d908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_tags'), table_name='articles')
    op.drop_column('articles', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_articles_tags'), 'articles', ['tags'], unique=False)
    # ### end Alembic commands ###
