"""add tags array to articles

Revision ID: 11bfda37d908
Revises: 146917599e25
Create Date: 2026-04-02 17:04:44.825567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11bfda37d908'
down_revision: Union[str, Sequence[str], None] = '146917599e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.create_index(op.f('ix_articles_tags'), 'articles', ['tags'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_tags'), table_name='articles')
    op.drop_column('articles', 'tags')
    # ### end Alembic commands ###
