"""add is_deleted to articles

Revision ID: 146917599e25
Revises: e86896104087
Create Date: 2026-04-02 11:01:03.112968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146917599e25'
down_revision: Union[str, Sequence[str], None] = 'e86896104087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True))
    op.create_index(op.f('ix_articles_is_deleted'), 'articles', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_is_deleted'), table_name='articles')
    op.drop_column('articles', 'is_deleted')
    # ### end Alembic commands ###
