"""add_computed_search_vector

Revision ID: 1d94c89f8bdc
Revises: 08154c1e22f4
Create Date: 2026-04-10 10:43:55.122549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d94c89f8bdc'
down_revision: Union[str, Sequence[str], None] = '08154c1e22f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', title || ' ' || coalesce(content, ''))", persisted=True), nullable=True))
    op.create_index('ix_article_search_vector', 'articles', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_search_vector', table_name='articles', postgresql_using='gin')
    op.drop_column('articles', 'search_vector')
    # ### end Alembic commands ###
